// <auto-generated />
using System;
using Lebetak.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lebetak.Migrations
{
    [DbContext(typeof(LebetakContext))]
    [Migration("20260104105842_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lebetak.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answer");
                });

            modelBuilder.Entity("Lebetak.Models.AttAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnswerId")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AnswerId");

                    b.ToTable("AttAnswer");
                });

            modelBuilder.Entity("Lebetak.Models.AttCompanyProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("AttCompanyProject");
                });

            modelBuilder.Entity("Lebetak.Models.AttPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.ToTable("AttPosts");
                });

            modelBuilder.Entity("Lebetak.Models.AttService", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ServiceId");

                    b.ToTable("AttService");
                });

            modelBuilder.Entity("Lebetak.Models.Att_Proposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProposalId")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProposalId");

                    b.ToTable("Att_Proposal");
                });

            modelBuilder.Entity("Lebetak.Models.Attachments.Att_Worker_Project.AttWorkerProject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("AttWorkerProjects");
                });

            modelBuilder.Entity("Lebetak.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("IconURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 0,
                            Name = "سباكة",
                            QuestionId = 0
                        },
                        new
                        {
                            Id = 2,
                            CompanyId = 0,
                            Name = "كهرباء",
                            QuestionId = 0
                        },
                        new
                        {
                            Id = 3,
                            CompanyId = 0,
                            Name = "نجارة",
                            QuestionId = 0
                        },
                        new
                        {
                            Id = 4,
                            CompanyId = 0,
                            Name = "دهان",
                            QuestionId = 0
                        },
                        new
                        {
                            Id = 5,
                            CompanyId = 0,
                            Name = "تكييف",
                            QuestionId = 0
                        },
                        new
                        {
                            Id = 6,
                            CompanyId = 0,
                            Name = "صيانة أجهزة منزلية",
                            QuestionId = 0
                        },
                        new
                        {
                            Id = 7,
                            CompanyId = 0,
                            Name = "تنظيف",
                            QuestionId = 0
                        },
                        new
                        {
                            Id = 8,
                            CompanyId = 0,
                            Name = "تصليح أثاث",
                            QuestionId = 0
                        },
                        new
                        {
                            Id = 9,
                            CompanyId = 0,
                            Name = "تركيب سيراميك وارضيات",
                            QuestionId = 0
                        },
                        new
                        {
                            Id = 10,
                            CompanyId = 0,
                            Name = "دهانات خارجية",
                            QuestionId = 0
                        },
                        new
                        {
                            Id = 11,
                            CompanyId = 0,
                            Name = "أعمال حدادة",
                            QuestionId = 0
                        },
                        new
                        {
                            Id = 12,
                            CompanyId = 0,
                            Name = "أعمال عزل",
                            QuestionId = 0
                        },
                        new
                        {
                            Id = 13,
                            CompanyId = 0,
                            Name = "أعمال الحدائق",
                            QuestionId = 0
                        },
                        new
                        {
                            Id = 14,
                            CompanyId = 0,
                            Name = "دهان داخلي",
                            QuestionId = 0
                        },
                        new
                        {
                            Id = 15,
                            CompanyId = 0,
                            Name = "خدمات طوارئ",
                            QuestionId = 0
                        });
                });

            modelBuilder.Entity("Lebetak.Models.ChatModel.Chat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("clientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId");

                    b.HasIndex("clientId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("Lebetak.Models.ChatModel.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFromClient")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReaded")
                        .HasColumnType("bit");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("chatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("chatId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Lebetak.Models.ChatNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("ChatNotifications");
                });

            modelBuilder.Entity("Lebetak.Models.Client", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Lebetak.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Panner")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Lebetak.Models.ComponyPhones", b =>
                {
                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("CompanyId", "PhoneNumber");

                    b.ToTable("ComponyPhones");
                });

            modelBuilder.Entity("Lebetak.Models.Option", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Option");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            QuestionId = 1,
                            Text = "تسريب"
                        },
                        new
                        {
                            Id = 2,
                            QuestionId = 1,
                            Text = "انسداد"
                        },
                        new
                        {
                            Id = 3,
                            QuestionId = 1,
                            Text = "كسر"
                        },
                        new
                        {
                            Id = 4,
                            QuestionId = 2,
                            Text = "مطبخ"
                        },
                        new
                        {
                            Id = 5,
                            QuestionId = 2,
                            Text = "حمام"
                        },
                        new
                        {
                            Id = 6,
                            QuestionId = 2,
                            Text = "سطح"
                        },
                        new
                        {
                            Id = 7,
                            QuestionId = 3,
                            Text = "فصل كهرباء"
                        },
                        new
                        {
                            Id = 8,
                            QuestionId = 3,
                            Text = "تماس"
                        },
                        new
                        {
                            Id = 9,
                            QuestionId = 3,
                            Text = "عطل فيوز"
                        },
                        new
                        {
                            Id = 10,
                            QuestionId = 4,
                            Text = "نعم"
                        },
                        new
                        {
                            Id = 11,
                            QuestionId = 4,
                            Text = "لا"
                        },
                        new
                        {
                            Id = 12,
                            QuestionId = 5,
                            Text = "تفصيل"
                        },
                        new
                        {
                            Id = 13,
                            QuestionId = 5,
                            Text = "تصليح"
                        },
                        new
                        {
                            Id = 14,
                            QuestionId = 5,
                            Text = "تركيب"
                        },
                        new
                        {
                            Id = 15,
                            QuestionId = 6,
                            Text = "خشب طبيعي"
                        },
                        new
                        {
                            Id = 16,
                            QuestionId = 6,
                            Text = "MDF"
                        },
                        new
                        {
                            Id = 17,
                            QuestionId = 6,
                            Text = "كونتر"
                        },
                        new
                        {
                            Id = 18,
                            QuestionId = 7,
                            Text = "بلاستيك"
                        },
                        new
                        {
                            Id = 19,
                            QuestionId = 7,
                            Text = "زيت"
                        },
                        new
                        {
                            Id = 20,
                            QuestionId = 7,
                            Text = "لاكيه"
                        },
                        new
                        {
                            Id = 21,
                            QuestionId = 8,
                            Text = "صغيرة"
                        },
                        new
                        {
                            Id = 22,
                            QuestionId = 8,
                            Text = "متوسطة"
                        },
                        new
                        {
                            Id = 23,
                            QuestionId = 8,
                            Text = "كبيرة"
                        },
                        new
                        {
                            Id = 24,
                            QuestionId = 9,
                            Text = "سبليت"
                        },
                        new
                        {
                            Id = 25,
                            QuestionId = 9,
                            Text = "شباك"
                        },
                        new
                        {
                            Id = 26,
                            QuestionId = 9,
                            Text = "مركزي"
                        },
                        new
                        {
                            Id = 27,
                            QuestionId = 10,
                            Text = "لا يبرد"
                        },
                        new
                        {
                            Id = 28,
                            QuestionId = 10,
                            Text = "تسريب"
                        },
                        new
                        {
                            Id = 29,
                            QuestionId = 10,
                            Text = "صوت عالي"
                        },
                        new
                        {
                            Id = 30,
                            QuestionId = 11,
                            Text = "غسالة"
                        },
                        new
                        {
                            Id = 31,
                            QuestionId = 11,
                            Text = "ثلاجة"
                        },
                        new
                        {
                            Id = 32,
                            QuestionId = 11,
                            Text = "بوتاجاز"
                        },
                        new
                        {
                            Id = 33,
                            QuestionId = 12,
                            Text = "لا يعمل"
                        },
                        new
                        {
                            Id = 34,
                            QuestionId = 12,
                            Text = "ضعف أداء"
                        },
                        new
                        {
                            Id = 35,
                            QuestionId = 12,
                            Text = "صوت غريب"
                        },
                        new
                        {
                            Id = 36,
                            QuestionId = 13,
                            Text = "منزل"
                        },
                        new
                        {
                            Id = 37,
                            QuestionId = 13,
                            Text = "مكتب"
                        },
                        new
                        {
                            Id = 38,
                            QuestionId = 13,
                            Text = "شركة"
                        },
                        new
                        {
                            Id = 39,
                            QuestionId = 14,
                            Text = "صغير"
                        },
                        new
                        {
                            Id = 40,
                            QuestionId = 14,
                            Text = "متوسط"
                        },
                        new
                        {
                            Id = 41,
                            QuestionId = 14,
                            Text = "كبير"
                        },
                        new
                        {
                            Id = 42,
                            QuestionId = 15,
                            Text = "كرسي"
                        },
                        new
                        {
                            Id = 43,
                            QuestionId = 15,
                            Text = "دولاب"
                        },
                        new
                        {
                            Id = 44,
                            QuestionId = 15,
                            Text = "سرير"
                        },
                        new
                        {
                            Id = 45,
                            QuestionId = 16,
                            Text = "كسر"
                        },
                        new
                        {
                            Id = 46,
                            QuestionId = 16,
                            Text = "فك"
                        },
                        new
                        {
                            Id = 47,
                            QuestionId = 16,
                            Text = "تلف"
                        },
                        new
                        {
                            Id = 48,
                            QuestionId = 17,
                            Text = "سيراميك"
                        },
                        new
                        {
                            Id = 49,
                            QuestionId = 17,
                            Text = "رخام"
                        },
                        new
                        {
                            Id = 50,
                            QuestionId = 17,
                            Text = "باركيه"
                        },
                        new
                        {
                            Id = 51,
                            QuestionId = 18,
                            Text = "صغيرة"
                        },
                        new
                        {
                            Id = 52,
                            QuestionId = 18,
                            Text = "متوسطة"
                        },
                        new
                        {
                            Id = 53,
                            QuestionId = 18,
                            Text = "كبيرة"
                        },
                        new
                        {
                            Id = 54,
                            QuestionId = 19,
                            Text = "منزل"
                        },
                        new
                        {
                            Id = 55,
                            QuestionId = 19,
                            Text = "فيلا"
                        },
                        new
                        {
                            Id = 56,
                            QuestionId = 19,
                            Text = "عمارة"
                        },
                        new
                        {
                            Id = 57,
                            QuestionId = 20,
                            Text = "جيدة"
                        },
                        new
                        {
                            Id = 58,
                            QuestionId = 20,
                            Text = "متشققة"
                        },
                        new
                        {
                            Id = 59,
                            QuestionId = 20,
                            Text = "تحتاج ترميم"
                        },
                        new
                        {
                            Id = 60,
                            QuestionId = 21,
                            Text = "أبواب"
                        },
                        new
                        {
                            Id = 61,
                            QuestionId = 21,
                            Text = "شبابيك"
                        },
                        new
                        {
                            Id = 62,
                            QuestionId = 21,
                            Text = "سلالم"
                        },
                        new
                        {
                            Id = 63,
                            QuestionId = 22,
                            Text = "داخلي"
                        },
                        new
                        {
                            Id = 64,
                            QuestionId = 22,
                            Text = "خارجي"
                        },
                        new
                        {
                            Id = 65,
                            QuestionId = 23,
                            Text = "مائي"
                        },
                        new
                        {
                            Id = 66,
                            QuestionId = 23,
                            Text = "حراري"
                        },
                        new
                        {
                            Id = 67,
                            QuestionId = 23,
                            Text = "صوتي"
                        },
                        new
                        {
                            Id = 68,
                            QuestionId = 24,
                            Text = "سطح"
                        },
                        new
                        {
                            Id = 69,
                            QuestionId = 24,
                            Text = "حمام"
                        },
                        new
                        {
                            Id = 70,
                            QuestionId = 24,
                            Text = "جدران"
                        },
                        new
                        {
                            Id = 71,
                            QuestionId = 25,
                            Text = "زراعة"
                        },
                        new
                        {
                            Id = 72,
                            QuestionId = 25,
                            Text = "قص"
                        },
                        new
                        {
                            Id = 73,
                            QuestionId = 25,
                            Text = "تنظيف"
                        },
                        new
                        {
                            Id = 74,
                            QuestionId = 26,
                            Text = "صغيرة"
                        },
                        new
                        {
                            Id = 75,
                            QuestionId = 26,
                            Text = "متوسطة"
                        },
                        new
                        {
                            Id = 76,
                            QuestionId = 26,
                            Text = "كبيرة"
                        },
                        new
                        {
                            Id = 77,
                            QuestionId = 27,
                            Text = "غرفة نوم"
                        },
                        new
                        {
                            Id = 78,
                            QuestionId = 27,
                            Text = "صالة"
                        },
                        new
                        {
                            Id = 79,
                            QuestionId = 27,
                            Text = "مطبخ"
                        },
                        new
                        {
                            Id = 80,
                            QuestionId = 28,
                            Text = "بلاستيك"
                        },
                        new
                        {
                            Id = 81,
                            QuestionId = 28,
                            Text = "زيت"
                        },
                        new
                        {
                            Id = 82,
                            QuestionId = 28,
                            Text = "لاكيه"
                        },
                        new
                        {
                            Id = 83,
                            QuestionId = 29,
                            Text = "كهرباء"
                        },
                        new
                        {
                            Id = 84,
                            QuestionId = 29,
                            Text = "مياه"
                        },
                        new
                        {
                            Id = 85,
                            QuestionId = 29,
                            Text = "تكييف"
                        },
                        new
                        {
                            Id = 86,
                            QuestionId = 30,
                            Text = "منخفضة"
                        },
                        new
                        {
                            Id = 87,
                            QuestionId = 30,
                            Text = "متوسطة"
                        },
                        new
                        {
                            Id = 88,
                            QuestionId = 30,
                            Text = "عالية"
                        });
                });

            modelBuilder.Entity("Lebetak.Models.Owner", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.HasKey("UserID");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("Lebetak.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BudgetFrom")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("BudgetTo")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(30)
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int?>("PostStatusId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UrgencyId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ClientId");

                    b.HasIndex("CreatedDate");

                    b.HasIndex("PostStatusId");

                    b.HasIndex("UrgencyId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Lebetak.Models.PostStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("PostStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "الإعلان مفتوح لتلقي العروض",
                            Title = "مفتوح"
                        },
                        new
                        {
                            Id = 2,
                            Description = "العمل قيد التنفيذ",
                            Title = "قيد التنفيذ"
                        },
                        new
                        {
                            Id = 3,
                            Description = "تم إكمال العمل بنجاح",
                            Title = "مكتمل"
                        });
                });

            modelBuilder.Entity("Lebetak.Models.ProjectCompany", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalReacts")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("ProjectCompanies");
                });

            modelBuilder.Entity("Lebetak.Models.ProjectWorker", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("TotalReacts")
                        .HasColumnType("int");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("WorkerId");

                    b.ToTable("ProjectWorkers");
                });

            modelBuilder.Entity("Lebetak.Models.Proposal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_At")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("RatingId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PostId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Proposal");
                });

            modelBuilder.Entity("Lebetak.Models.ProposalNotification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("ProposalNotifications");
                });

            modelBuilder.Entity("Lebetak.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Question");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Text = "نوع المشكلة؟"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Text = "مكان المشكلة؟"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Text = "نوع العطل الكهربائي؟"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Text = "هل يوجد انقطاع كامل؟"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Text = "نوع العمل المطلوب؟"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Text = "نوع الخشب؟"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Text = "نوع الدهان؟"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Text = "مساحة المكان؟"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Text = "نوع جهاز التكييف؟"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Text = "نوع المشكلة؟"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            Text = "نوع الجهاز؟"
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 6,
                            Text = "نوع العطل؟"
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 7,
                            Text = "نوع التنظيف؟"
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 7,
                            Text = "حجم المكان؟"
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 8,
                            Text = "نوع الأثاث؟"
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 8,
                            Text = "نوع الضرر؟"
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 9,
                            Text = "نوع الأرضية؟"
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 9,
                            Text = "مساحة العمل؟"
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 10,
                            Text = "نوع المبنى؟"
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 10,
                            Text = "حالة الجدران؟"
                        },
                        new
                        {
                            Id = 21,
                            CategoryId = 11,
                            Text = "نوع العمل؟"
                        },
                        new
                        {
                            Id = 22,
                            CategoryId = 11,
                            Text = "مكان التنفيذ؟"
                        },
                        new
                        {
                            Id = 23,
                            CategoryId = 12,
                            Text = "نوع العزل؟"
                        },
                        new
                        {
                            Id = 24,
                            CategoryId = 12,
                            Text = "مكان العزل؟"
                        },
                        new
                        {
                            Id = 25,
                            CategoryId = 13,
                            Text = "نوع الخدمة؟"
                        },
                        new
                        {
                            Id = 26,
                            CategoryId = 13,
                            Text = "مساحة الحديقة؟"
                        },
                        new
                        {
                            Id = 27,
                            CategoryId = 14,
                            Text = "نوع الغرفة؟"
                        },
                        new
                        {
                            Id = 28,
                            CategoryId = 14,
                            Text = "نوع الدهان؟"
                        },
                        new
                        {
                            Id = 29,
                            CategoryId = 15,
                            Text = "نوع الطوارئ؟"
                        },
                        new
                        {
                            Id = 30,
                            CategoryId = 15,
                            Text = "درجة الخطورة؟"
                        });
                });

            modelBuilder.Entity("Lebetak.Models.Rating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ProposalId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Value")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("ProposalId")
                        .IsUnique();

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("Lebetak.Models.Report", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkerId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("WorkerId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("Lebetak.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClientId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("PreferredTime")
                        .HasMaxLength(50)
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CompanyId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Lebetak.Models.ServiceAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OptionId")
                        .HasColumnType("int");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OptionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("ServiceId", "QuestionId")
                        .IsUnique();

                    b.ToTable("ServiceAnswers");
                });

            modelBuilder.Entity("Lebetak.Models.Skill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("Lebetak.Models.Urgency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Urgencies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "احتاج تنفيذ هذة الخدمة في اسرع وقت",
                            Title = "مستعجل"
                        },
                        new
                        {
                            Id = 2,
                            Description = "يمكن تنفيذ الخدمة في وقت لاحق",
                            Title = "غير مستعجل"
                        },
                        new
                        {
                            Id = 3,
                            Description = "يمكن تنفيذ الخدمة خلال اليوم",
                            Title = "عادي"
                        },
                        new
                        {
                            Id = 4,
                            Description = "يجب تنفيذ الخدمة خلال 24 ساعة",
                            Title = "هام"
                        });
                });

            modelBuilder.Entity("Lebetak.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ApartmentNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("F_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEmailDisabled")
                        .HasColumnType("bit");

                    b.Property<string>("L_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocationURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSN_BackURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SSN_FrontURL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<double>("latitude")
                        .HasColumnType("float");

                    b.Property<double>("longitude")
                        .HasColumnType("float");

                    b.Property<string>("profileImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Lebetak.Models.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets");
                });

            modelBuilder.Entity("Lebetak.Models.Worker", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("ExperienceYears")
                        .HasColumnType("int");

                    b.Property<int>("HourlyPrice")
                        .HasColumnType("int");

                    b.Property<bool>("Is_Avilable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("Is_Booked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("Is_Online")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("NumberOfRates")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.HasKey("UserId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Workers");
                });

            modelBuilder.Entity("Lebetak.Models.WorkerSkills", b =>
                {
                    b.Property<int>("SkillId")
                        .HasColumnType("int");

                    b.Property<string>("WorkerId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("SkillId", "WorkerId");

                    b.HasIndex("WorkerId");

                    b.ToTable("WorkerSkills");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Client",
                            NormalizedName = "CLIENT"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Worker",
                            NormalizedName = "WORKER"
                        },
                        new
                        {
                            Id = "4",
                            Name = "Owner",
                            NormalizedName = "OWNER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Lebetak.Models.Answer", b =>
                {
                    b.HasOne("Lebetak.Models.Question", "question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("question");
                });

            modelBuilder.Entity("Lebetak.Models.AttAnswer", b =>
                {
                    b.HasOne("Lebetak.Models.Answer", "Answer")
                        .WithMany("attAnswers")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Answer");
                });

            modelBuilder.Entity("Lebetak.Models.AttCompanyProject", b =>
                {
                    b.HasOne("Lebetak.Models.ProjectCompany", "Project")
                        .WithMany("Images")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Lebetak.Models.AttPost", b =>
                {
                    b.HasOne("Lebetak.Models.Post", "Post")
                        .WithMany("AttPosts")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Post");
                });

            modelBuilder.Entity("Lebetak.Models.AttService", b =>
                {
                    b.HasOne("Lebetak.Models.Service", "Service")
                        .WithMany("AttService")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Lebetak.Models.Att_Proposal", b =>
                {
                    b.HasOne("Lebetak.Models.Proposal", "Proposal")
                        .WithMany("Images")
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("Lebetak.Models.Attachments.Att_Worker_Project.AttWorkerProject", b =>
                {
                    b.HasOne("Lebetak.Models.ProjectWorker", "Project")
                        .WithMany("Images")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Lebetak.Models.ChatModel.Chat", b =>
                {
                    b.HasOne("Lebetak.Models.Worker", "Worker")
                        .WithMany("Chats")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lebetak.Models.Client", "client")
                        .WithMany("Chats")
                        .HasForeignKey("clientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Worker");

                    b.Navigation("client");
                });

            modelBuilder.Entity("Lebetak.Models.ChatModel.Message", b =>
                {
                    b.HasOne("Lebetak.Models.ChatModel.Chat", "Chat")
                        .WithMany("Messages")
                        .HasForeignKey("chatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chat");
                });

            modelBuilder.Entity("Lebetak.Models.Client", b =>
                {
                    b.HasOne("Lebetak.Models.User", "User")
                        .WithOne("Client")
                        .HasForeignKey("Lebetak.Models.Client", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lebetak.Models.Company", b =>
                {
                    b.HasOne("Lebetak.Models.Category", "Category")
                        .WithMany("Companies")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Lebetak.Models.Owner", "Owner")
                        .WithOne("Company")
                        .HasForeignKey("Lebetak.Models.Company", "OwnerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("Lebetak.Models.ComponyPhones", b =>
                {
                    b.HasOne("Lebetak.Models.Company", "Company")
                        .WithMany("ComponyPhones")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Lebetak.Models.Option", b =>
                {
                    b.HasOne("Lebetak.Models.Question", "Question")
                        .WithMany("options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Lebetak.Models.Owner", b =>
                {
                    b.HasOne("Lebetak.Models.User", "User")
                        .WithOne("Owner")
                        .HasForeignKey("Lebetak.Models.Owner", "UserID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lebetak.Models.Post", b =>
                {
                    b.HasOne("Lebetak.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Lebetak.Models.Client", "Client")
                        .WithMany("Posts")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Lebetak.Models.PostStatus", null)
                        .WithMany("Posts")
                        .HasForeignKey("PostStatusId");

                    b.HasOne("Lebetak.Models.Urgency", "Urgency")
                        .WithMany("Posts")
                        .HasForeignKey("UrgencyId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Client");

                    b.Navigation("Urgency");
                });

            modelBuilder.Entity("Lebetak.Models.ProjectCompany", b =>
                {
                    b.HasOne("Lebetak.Models.Company", "Company")
                        .WithMany("Projects")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Lebetak.Models.ProjectWorker", b =>
                {
                    b.HasOne("Lebetak.Models.Worker", "Worker")
                        .WithMany("Projects")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Lebetak.Models.Proposal", b =>
                {
                    b.HasOne("Lebetak.Models.Post", "Post")
                        .WithMany("Proposals")
                        .HasForeignKey("PostId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lebetak.Models.Worker", "Worker")
                        .WithMany("Proposals")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Post");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Lebetak.Models.Question", b =>
                {
                    b.HasOne("Lebetak.Models.Category", "Category")
                        .WithMany("Questions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Lebetak.Models.Rating", b =>
                {
                    b.HasOne("Lebetak.Models.Proposal", "Proposal")
                        .WithOne("Rating")
                        .HasForeignKey("Lebetak.Models.Rating", "ProposalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("Lebetak.Models.Report", b =>
                {
                    b.HasOne("Lebetak.Models.Client", "Client")
                        .WithMany("Reports")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lebetak.Models.Worker", "Worker")
                        .WithMany("Reports")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Lebetak.Models.Service", b =>
                {
                    b.HasOne("Lebetak.Models.Client", "Client")
                        .WithMany("Services")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Lebetak.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Lebetak.Models.ServiceAnswer", b =>
                {
                    b.HasOne("Lebetak.Models.Option", "Option")
                        .WithMany()
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Lebetak.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Lebetak.Models.Service", "Service")
                        .WithMany("ServiceAnswers")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Option");

                    b.Navigation("Question");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Lebetak.Models.Wallet", b =>
                {
                    b.HasOne("Lebetak.Models.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("Lebetak.Models.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lebetak.Models.Worker", b =>
                {
                    b.HasOne("Lebetak.Models.Category", "Category")
                        .WithMany("Workers")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lebetak.Models.User", "User")
                        .WithOne("Worker")
                        .HasForeignKey("Lebetak.Models.Worker", "UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Lebetak.Models.WorkerSkills", b =>
                {
                    b.HasOne("Lebetak.Models.Skill", "Skill")
                        .WithMany("WorkerSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lebetak.Models.Worker", "Worker")
                        .WithMany("WorkerSkills")
                        .HasForeignKey("WorkerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Skill");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Lebetak.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Lebetak.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lebetak.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Lebetak.Models.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Lebetak.Models.Answer", b =>
                {
                    b.Navigation("attAnswers");
                });

            modelBuilder.Entity("Lebetak.Models.Category", b =>
                {
                    b.Navigation("Companies");

                    b.Navigation("Posts");

                    b.Navigation("Questions");

                    b.Navigation("Workers");
                });

            modelBuilder.Entity("Lebetak.Models.ChatModel.Chat", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("Lebetak.Models.Client", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Posts");

                    b.Navigation("Reports");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("Lebetak.Models.Company", b =>
                {
                    b.Navigation("ComponyPhones");

                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Lebetak.Models.Owner", b =>
                {
                    b.Navigation("Company");
                });

            modelBuilder.Entity("Lebetak.Models.Post", b =>
                {
                    b.Navigation("AttPosts");

                    b.Navigation("Proposals");
                });

            modelBuilder.Entity("Lebetak.Models.PostStatus", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Lebetak.Models.ProjectCompany", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Lebetak.Models.ProjectWorker", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Lebetak.Models.Proposal", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("Rating");
                });

            modelBuilder.Entity("Lebetak.Models.Question", b =>
                {
                    b.Navigation("options");
                });

            modelBuilder.Entity("Lebetak.Models.Service", b =>
                {
                    b.Navigation("AttService");

                    b.Navigation("ServiceAnswers");
                });

            modelBuilder.Entity("Lebetak.Models.Skill", b =>
                {
                    b.Navigation("WorkerSkills");
                });

            modelBuilder.Entity("Lebetak.Models.Urgency", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Lebetak.Models.User", b =>
                {
                    b.Navigation("Client");

                    b.Navigation("Owner");

                    b.Navigation("Wallet");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("Lebetak.Models.Worker", b =>
                {
                    b.Navigation("Chats");

                    b.Navigation("Projects");

                    b.Navigation("Proposals");

                    b.Navigation("Reports");

                    b.Navigation("WorkerSkills");
                });
#pragma warning restore 612, 618
        }
    }
}
